name: Django CI/CD to Render

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: pet_health_db_9k05
          POSTGRES_USER: admin01
          POSTGRES_PASSWORD: BqPuom2y6FWdK2TbUJ8HioA6nEXh85G8
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 🟢 1. สเต็ปที่ต้องเพิ่ม: ติดตั้งไลบรารีฐานข้อมูลให้เครื่อง Ubuntu ของ GitHub ก่อน
    - name: Install PostgreSQL Client Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev postgresql-client

    - name: Install Dependencies
      env:
        DB_NAME: 'pet_health_db_9k05'
        DB_USER: 'admin01'
        DB_PASSWORD: 'BqPuom2y6FWdK2TbUJ8HioA6nEXh85G8'
        DB_HOST: 'localhost'
        DB_PORT: '5432'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django System Check
      env:
        DB_NAME: 'pet_health_db_9k05'
        DB_USER: 'admin01'
        DB_PASSWORD: 'BqPuom2y6FWdK2TbUJ8HioA6nEXh85G8'
        DB_HOST: 'localhost'
        DB_PORT: '5432'
      run: |
        python manage.py check

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"