# Generated by Django 6.0.5 on 2026-05-18 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสัตว์เลี้ยง')),
                ('pet_type', models.CharField(choices=[('DOG', 'สุนัข'), ('CAT', 'แมว'), ('RABBIT', 'กระต่าย'), ('OTHER', 'อื่นๆ')], default='DOG', max_length=10, verbose_name='ประเภทสัตว์เลี้ยง')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='สายพันธุ์')),
                ('birth_date', models.DateField(verbose_name='วันเกิด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของ')),
            ],
            options={
                'verbose_name': 'สัตว์เลี้ยง',
                'verbose_name_plural': 'ข้อมูลสัตว์เลี้ยง',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่บันทึก')),
                ('note', models.TextField(verbose_name='บันทึกกิจกรรมประจำวัน')),
                ('weight_recorded', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='น้ำหนักที่ชั่งได้ (กก.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='pets.pet', verbose_name='สัตว์เลี้ยง')),
            ],
            options={
                'verbose_name': 'ไดอารี่ประจำวัน',
                'verbose_name_plural': 'บันทึกไดอารี่ประจำวัน',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อนัดหมาย/กิจกรรม')),
                ('due_date', models.DateField(verbose_name='วันที่นัดหมาย')),
                ('is_completed', models.BooleanField(default=False, verbose_name='ทำสำเร็จแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet', verbose_name='สัตว์เลี้ยง')),
            ],
            options={
                'verbose_name': 'นัดหมาย',
                'verbose_name_plural': 'รายการนัดหมายและกิจกรรม',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่กิน')),
                ('calories_consumed', models.IntegerField(default=0, verbose_name='แคลอรีที่กินไป (kcal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to='pets.pet', verbose_name='สัตว์เลี้ยง')),
            ],
            options={
                'verbose_name': 'บันทึกการกิน',
                'verbose_name_plural': 'บันทึกโภชนาการประจำวัน',
                'unique_together': {('pet', 'date')},
            },
        ),
    ]
