# Generated by Django 6.0.5 on 2026-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', '♂ ผู้'), ('F', '♀ เมีย')], default='M', max_length=2, verbose_name='เพศ'),
        ),
    ]
