# Generated by Django 6.0.5 on 2026-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='อารมณ์'),
        ),
    ]
