# Generated by Django 6.0.5 on 2026-05-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_nutritionlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ปริมาณ'),
        ),
    ]
