# Generated by Django 6.0.5 on 2026-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_nutritionlog_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลา'),
        ),
    ]
