# Generated by Django on %s
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_appointment_note_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='calorie_goal',
            field=models.IntegerField(default=0, verbose_name='เป้าหมายแคลอรี/วัน (kcal)'),
        ),
    ]
